[workspace]
resolver = "2"
members = ["crates/*"]

# We want to reduce the size of build outputs in the CI to increase the effectiveness
# of the cache. Hence we need to apply some basic optimizations and disable everything
# that increases binary size.
[profile.debug-ci]
inherits = "dev"
opt-level = 1
incremental = false
debug = false
panic = "abort"

[patch.'https://github.com/w3f/fflonk']
fflonk = { git = "https://www.github.com/w3f/fflonk", rev = "be95d4c971b1d15b5badfc06ff13f5c07987d484" }
