[package]
name = "contract-analyze"
version = "4.1.1-ethink.1"
authors = ["Use Ink <ink@r0gue.io>", "Alexander Gryaznov <hi@agryaznov.com>"]
edition = "2021"

license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/paritytech/cargo-contract"
documentation = "https://docs.rs/contract-analyze"
homepage = "https://www.substrate.io/"
description = "Library determining source language for smart contracts on substrate"
keywords = ["wasm", "parity", "webassembly", "blockchain", "edsl"]
include = ["Cargo.toml", "*.rs", "LICENSE"]

[dependencies]
contract-metadata = { version = "4.1.1-ethink.1", path = "../metadata" }
wasmparser = "0.207.0"
anyhow = "1.0.83"

[dev-dependencies]
wat = "1.207.0"

